import pytest

from backend.schemas.dataset_profile import DatasetProfile, ColumnProfileExtended
from backend.schemas.decision import DecisionDomain, DecisionSource
from backend.schemas.preprocessing_plan import PreprocessingStep, PreprocessingPlan, PlanValidationResult
from backend.engine.preprocessing_plan_builder import PreprocessingPlanBuilder
from backend.engine.plan_validator import PlanValidator


def test_valid_preprocessing_plan_passes_validation():
    """Verify a clean PreprocessingPlan passes PlanValidator cleanly."""
    step1 = PreprocessingStep(
        step_number=1,
        domain=DecisionDomain.MISSING_VALUE_STRATEGY,
        action="IMPUTE_MEDIAN",
        columns=["age"],
        decision_id="dec_101",
        decision_source=DecisionSource.RULE,
        confidence=0.95,
    )
    step2 = PreprocessingStep(
        step_number=2,
        domain=DecisionDomain.SCALING_TRANSFORMATION,
        action="STANDARD_SCALER",
        columns=["income"],
        decision_id="dec_102",
        decision_source=DecisionSource.RULE,
        confidence=0.90,
    )

    plan = PreprocessingPlan(
        dataset_name="census",
        target_column="income_bracket",
        steps=[step1, step2],
    )

    validator = PlanValidator()
    result = validator.validate_plan(plan)

    assert result.is_valid is True
    assert len(result.errors) == 0
    assert result.validated_step_count == 2


def test_target_leakage_detection():
    """Verify target column transformation triggers target leakage validation error."""
    step_leak = PreprocessingStep(
        step_number=1,
        domain=DecisionDomain.MISSING_VALUE_STRATEGY,
        action="IMPUTE_MEAN",
        columns=["target_col"],  # Target column passed as feature column to impute!
        decision_id="dec_leak",
        decision_source=DecisionSource.RULE,
        confidence=0.80,
    )

    plan = PreprocessingPlan(
        dataset_name="leakage_test",
        target_column="target_col",
        steps=[step_leak],
    )

    validator = PlanValidator()
    result = validator.validate_plan(plan)

    assert result.is_valid is False
    assert any("Target Leakage Error" in err for err in result.errors)


def test_unsupported_action_detection():
    """Verify unsupported action triggers validation error."""
    step_bad = PreprocessingStep(
        step_number=1,
        domain=DecisionDomain.ENCODING_STRATEGY,
        action="MAGIC_QUANTUM_ENCODE",
        columns=["city"],
        decision_id="dec_bad",
        decision_source=DecisionSource.RULE,
        confidence=0.50,
    )

    plan = PreprocessingPlan(dataset_name="bad_action", steps=[step_bad])

    validator = PlanValidator()
    result = validator.validate_plan(plan)

    assert result.is_valid is False
    assert any("Unsupported or invalid action" in err for err in result.errors)


def test_dropped_column_contradiction_detection():
    """Verify referencing a dropped column in a subsequent step triggers contradiction error."""
    step_drop = PreprocessingStep(
        step_number=1,
        domain=DecisionDomain.FEATURE_SELECTION,
        action="DROP_COLUMNS",
        columns=["old_feature"],
        decision_id="dec_drop",
        decision_source=DecisionSource.RULE,
        confidence=0.99,
    )
    step_scale = PreprocessingStep(
        step_number=2,
        domain=DecisionDomain.SCALING_TRANSFORMATION,
        action="STANDARD_SCALER",
        columns=["old_feature"],  # Old feature was dropped in step 1!
        decision_id="dec_scale",
        decision_source=DecisionSource.RULE,
        confidence=0.90,
    )

    plan = PreprocessingPlan(dataset_name="contradiction_test", steps=[step_drop, step_scale])

    validator = PlanValidator()
    result = validator.validate_plan(plan)

    assert result.is_valid is False
    assert any("Contradiction Error" in err for err in result.errors)


def test_builder_and_validator_integration():
    """Verify plans generated by PreprocessingPlanBuilder pass PlanValidator."""
    col_age = ColumnProfileExtended(name="age", normalized_dtype="numeric", missing_ratio=0.10, skewness=0.1)
    col_city = ColumnProfileExtended(name="city", normalized_dtype="categorical", distinct_count=5)

    dataset_prof = DatasetProfile(
        dataset_name="housing",
        rows=500,
        columns=2,
        detailed_column_profiles=[col_age, col_city],
        target_column="price",
    )

    builder = PreprocessingPlanBuilder()
    plan = builder.build_plan(dataset_prof)

    validator = PlanValidator()
    val_res = validator.validate_plan(plan, dataset_profile=dataset_prof)

    assert val_res.is_valid is True
    assert len(val_res.errors) == 0
    assert val_res.validated_step_count > 0
